### PR TITLE
Release `v1.6.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v1.6.0` release.
Here you can find all related translations changes: [v1.5.0...master](https://github.com/flarum-lang/vietnamese/compare/v1.5.0...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## v1.6.0

**Thay đổi chung**:

* Đã cập nhật các bản dịch Flarum core.

**Đã thêm hỗ trợ cho các tiện ích mở rộng mới**:

* [`blomstra/conversations`](https://github.com/blomstra/flarum-ext-conversations)
* [`blomstra/turnstile`](https://github.com/blomstra/flarum-ext-turnstile)
* [`clarkwinkelmann/flarum-ext-meilisearch-dashboard`](https://github.com/clarkwinkelmann/flarum-ext-meilisearch-dashboard)
* [`clarkwinkelmann/flarum-ext-sudo-mode`](https://github.com/clarkwinkelmann/flarum-ext-sudo-mode)
* [`club-1/flarum-ext-cross-references`](https://github.com/club-1/flarum-ext-cross-references)
* [`datlechin/flarum-birthdays-widget`](https://github.com/datlechin/flarum-birthdays-widget)
* [`finteger/ratings`](https://github.com/finteger/ratings)
* [`ianm/log-viewer`](https://github.com/imorland/flarum-ext-log-viewer)
* [`ianm/oauth-line`](https://github.com/imorland/flarum-ext-oauth-line)
* [`ianm/oauth-twitch`](https://github.com/imorland/flarum-ext-oauth-twitch)
* [`justoverclock/discussion-tags`](https://extiverse.com/extension/justoverclock/discussion-tags)
* [`justoverclock/staff-members-widget`](https://github.com/justoverclockl/staff-member-widget)
* [`ziiven/flarum-daily-check-in`](https://github.com/Ziiven/flarum-daily-check-in)
* [`ziiven/flarum-post-number`](https://github.com/Ziiven/flarum-post-number)
* [`ziiven/view-history`](https://github.com/Ziiven/view-history)

**Đã cập nhật bản dịch cho các tiện ích mở rộng**:

* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/realtime`](https://extiverse.com/extension/blomstra/realtime)
* [`blomstra/search`](https://github.com/blomstra/flarum-ext-search)
* [`clarkwinkelmann/flarum-ext-passwordless`](https://github.com/clarkwinkelmann/flarum-ext-passwordless)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`datlechin/flarum-signup-button`](https://github.com/datlechin/flarum-signup-button)
* [`davwheat/virtual-authors`](https://extiverse.com/extension/davwheat/virtual-authors)
* [`flamarkt/backoffice`](https://github.com/flamarkt/backoffice)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`fof/ban-ips`](https://github.com/FriendsOfFlarum/ban-ips)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/default-user-preferences`](https://github.com/FriendsOfFlarum/default-user-preferences)
* [`fof/gamification`](https://github.com/FriendsOfFlarum/gamification)
* [`fof/geoip`](https://github.com/FriendsOfFlarum/geoip)
* [`fof/oauth`](https://github.com/FriendsOfFlarum/oauth)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`justoverclock/discussion-info`](https://github.com/justoverclockl/discussions-info)
* [`kilowhat/flarum-ext-audit-free`](https://github.com/kilowhat/flarum-ext-audit-free)
* [`kilowhat/flarum-ext-audit-pro`](https://extiverse.com/extension/kilowhat/flarum-ext-audit-pro)
* [`kilowhat/flarum-ext-formulaire`](https://extiverse.com/extension/kilowhat/flarum-ext-formulaire)
* [`maicol07/flarum-ext-sso`](https://github.com/maicol07/flarum-ext-sso)
* [`malago/flarum-achievements`](https://github.com/malago86/flarum-achievements)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`v17development/flarum-support`](https://extiverse.com/extension/v17development/flarum-support)

Tất cả các thay đổi: [v1.5.0...v1.6.0](https://github.com/flarum-lang/vietnamese/compare/v1.5.0...v1.6.0).

</details>

### CODE REVIEW

**Comment by datlechin** [comment]
Hi @rob006
I want the version is 1.5.1, how to do it

**Comment by rob006** [comment]
Why do you want this to be 1.5.1? Bot follows semver in this case: translations for new extension = new feature = minor release.

**Comment by datlechin** [comment]
Got it

**Review by datlechin — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/d/28471):

~~~markdown
## Phiên bản [`v1.6.0`](https://github.com/flarum-lang/vietnamese/releases/tag/v1.6.0)

**Thay đổi chung**:

* Đã cập nhật các bản dịch Flarum core.


**Đã thêm hỗ trợ cho các tiện ích mở rộng mới**:

* [`blomstra/conversations`](https://github.com/blomstra/flarum-ext-conversations)
* [`blomstra/turnstile`](https://github.com/blomstra/flarum-ext-turnstile)
* [`clarkwinkelmann/flarum-ext-meilisearch-dashboard`](https://github.com/clarkwinkelmann/flarum-ext-meilisearch-dashboard)
* [`clarkwinkelmann/flarum-ext-sudo-mode`](https://github.com/clarkwinkelmann/flarum-ext-sudo-mode)
* [`club-1/flarum-ext-cross-references`](https://github.com/club-1/flarum-ext-cross-references)
* [`datlechin/flarum-birthdays-widget`](https://github.com/datlechin/flarum-birthdays-widget)
* [`finteger/ratings`](https://github.com/finteger/ratings)
* [`ianm/log-viewer`](https://github.com/imorland/flarum-ext-log-viewer)
* [`ianm/oauth-line`](https://github.com/imorland/flarum-ext-oauth-line)
* [`ianm/oauth-twitch`](https://github.com/imorland/flarum-ext-oauth-twitch)
* [`justoverclock/discussion-tags`](https://extiverse.com/extension/justoverclock/discussion-tags)
* [`justoverclock/staff-members-widget`](https://github.com/justoverclockl/staff-member-widget)
* [`ziiven/flarum-daily-check-in`](https://github.com/Ziiven/flarum-daily-check-in)
* [`ziiven/flarum-post-number`](https://github.com/Ziiven/flarum-post-number)
* [`ziiven/view-history`](https://github.com/Ziiven/view-history)


**Đã cập nhật bản dịch cho các tiện ích mở rộng**:

* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/realtime`](https://extiverse.com/extension/blomstra/realtime)
* [`blomstra/search`](https://github.com/blomstra/flarum-ext-search)
* [`clarkwinkelmann/flarum-ext-passwordless`](https://github.com/clarkwinkelmann/flarum-ext-passwordless)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`datlechin/flarum-signup-button`](https://github.com/datlechin/flarum-signup-button)
* [`davwheat/virtual-authors`](https://extiverse.com/extension/davwheat/virtual-authors)
* [`flamarkt/backoffice`](https://github.com/flamarkt/backoffice)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`fof/ban-ips`](https://github.com/FriendsOfFlarum/ban-ips)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/default-user-preferences`](https://github.com/FriendsOfFlarum/default-user-preferences)
* [`fof/gamification`](https://github.com/FriendsOfFlarum/gamification)
* [`fof/geoip`](https://github.com/FriendsOfFlarum/geoip)
* [`fof/oauth`](https://github.com/FriendsOfFlarum/oauth)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`justoverclock/discussion-info`](https://github.com/justoverclockl/discussions-info)
* [`kilowhat/flarum-ext-audit-free`](https://github.com/kilowhat/flarum-ext-audit-free)
* [`kilowhat/flarum-ext-audit-pro`](https://extiverse.com/extension/kilowhat/flarum-ext-audit-pro)
* [`kilowhat/flarum-ext-formulaire`](https://extiverse.com/extension/kilowhat/flarum-ext-formulaire)
* [`maicol07/flarum-ext-sso`](https://github.com/maicol07/flarum-ext-sso)
* [`malago/flarum-achievements`](https://github.com/malago86/flarum-achievements)
* [`michaelbelgium/flarum-discussion-views`](https://github.com/MichaelBelgium/flarum-discussion-views)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`v17development/flarum-support`](https://extiverse.com/extension/v17development/flarum-support)


Tất cả các thay đổi: [v1.5.0...v1.6.0](https://github.com/flarum-lang/vietnamese/compare/v1.5.0...v1.6.0).

Để cập nhật, hãy chạy các lệnh sau:

```console
composer update flarum-lang/vietnamese
php flarum cache:clear
```

~~~

**Pull request merged**
